/**
 * VelociForge Multi-Format Exporter Engine
 */

const fs = require('fs');
const path = require('path');
const { Logger } = require('../utils/logger');

class ExporterEngine {
    static exportDockerLayer(projectDir = process.cwd()) {
        const bundlePath = path.join(projectDir, '.vforge');
        if (!fs.existsSync(bundlePath)) {
            throw new Error("No .vforge bundle found to export.");
        }

        const dockerfileContent = `# Generated by VelociForge Engine
FROM node:20-alpine AS base
WORKDIR /app

# Copy VelociForge virtual archive & manifest
COPY .vforge .vforge.json ./

# Install VelociForge global CLI & restore in sub-milliseconds
RUN npm install -g velociforge && vforge ci

# Copy application source code
COPY . .

CMD ["npm", "start"]
`;

        const dockerfilePath = path.join(projectDir, 'Dockerfile.vforge');
        fs.writeFileSync(dockerfilePath, dockerfileContent, 'utf8');

        Logger.success(`Generated optimized Dockerfile layer at: ${dockerfilePath}`);
        return dockerfilePath;
    }
}

module.exports = ExporterEngine;
